### ISSUE TITLE
Fix markdown syntax highlighting & suggestion

### ISSUE THREAD

**Issue by smartin015** [Fabricate-IO/expedition-quest-ide#15]
Make mods to the highlighting rules for markdown to allow for nested bullets:

https://github.com/ajaxorg/ace/blob/2499c8be56a2fbd41e5f051d39aec327d2f237ad/lib/ace/mode/markdown_highlight_rules.js

Also turn off bulleted list continuation when Enter is pressed (as it's usually not what we want)

**Comment by toddmedema** [comment]
While we're playing with syntax highlighting here, might also be nice to emphasize TODO blocks

(that being said, this is generally a lower priority issue, just noting while I was thinking of it)

**Comment by toddmedema** [comment]
Fixed
