### ISSUE TITLE
UI: top bar should always be visible

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-ide#28]
Right now, the ace text editor is the size of the full window, and the top bar is extra height on top of that. Because of that, if you scroll to the bottom of the text editor, the top bar disappears. This gets especially annoying with long quests.

Would be better to have the Ace editor window only be the height of the area below the top bar, so that the page doesn't have a separate scrollbar.

Also, top bar could probably be a bit shorter / doesn't need to be quite so tall

**Comment by smartin015** [comment]
This was fixed in the Great Preview Merge (#39)
