### ISSUE TITLE
Big: Properly separating XML and Markdown

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-ide#30]
Overview:

We want users to be able to write in and save Markdown freely, and not need to worry about XML until they publish.

Discuss: should we also build in a sense of "beta" vs "production" while we're building the publish API? Otherwise, how would quest creators safely debug / improve quests that they've already published?

What that looks like:

Editor UI:
- removing the view tabs (but keep the code, we'll have other views later like graph), always and only show Markdown view
  - saving and auto-saving should not even convert to XML / shouldn't throw errors if invalid
- new "publish" button that hits the publish API

Editor back-end:
- saving should save Markdown into a new column / spot in the datastore. In the future, with version control, this is what we'd store multiple versions of
- new "publish" API command that takes the latest saved version of Markdown, converts to XML, throws any / all conversion errors. Otherwise, if no errors, saves the converted XML to the current spot in the datastore where the app fetches quests. Also updates the `updated` timestamp for that quest.

**Comment by smartin015** [comment]
Obsolete bug is obsolete :) We now save markdown to Drive and export XML on publish. No XML is visible in the editor.
