### ISSUE TITLE
bug: choices extending across newlines

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-quest-ide#50]
```
_title_

goop

* BOB
Hello
* JOE
```

Renders a button with the text `BOB Hello * Joe`

**Comment by smartin015** [comment]
This is actually to spec with markdown - If there's no whitespace between a bullet and the next line, it's treated as inline with the bullet. Helps with styling extra-long bullet items.

https://daringfireball.net/projects/markdown/syntax#p

**Comment by toddmedema** [comment]
Ah, interesting
